name: set release branch
run-name: set release branch for ${{ github.event.inputs.version }} by ${{ github.actor }} on ${{ github.event.created_at }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input Release version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  create_release_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Validate version format
      run: |
        if ! echo "${{ github.event.inputs.version }}" | grep -qE '^\d+\.\d+\.\d+$'; then
          echo "Invalid version format. Please use the format: major.minor.patch (e.g., 1.0.0)"
          exit 1
        fi

    - uses: actions/checkout@v4
      with:
        ref: development

    - name: Update version in pubspec.yaml
      if:
      run: |
        sed -i -e "s/^version:.*/version: ${{ github.event.inputs.version }}/" pubspec.yaml

    - name: Create release branch
      run: |
        git checkout -b release/${{ github.event.inputs.version }}
        git add pubspec.yaml
        git commit -m "Increment version to ${{ github.event.inputs.version }}"
        git push origin release/${{ github.event.inputs.version }}
