name: set release branch
run-name: set release branch for ${{ github.event.inputs.version }}
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'input Release version (e.g. 1.0.0)'
        required: true
        type: string

jobs:
  create_release_branch:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_VERSION: ${{ github.event.inputs.version }}

    steps:
    - name: Validate input version format
      run: |
        if [[ !  "${{ env.RELEASE_VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Invalid version format. Please use the format: major.minor.patch (e.g., 1.0.0)"
          exit 1
        fi

    - name: Check out code
      uses: actions/checkout@v4
      with:
        ref: development

    - name: Update version in pubspec.yaml
      if:
      run: |
        sed -i -e "s/^version:.*/version: ${{ env.RELEASE_VERSION }}/" pubspec.yaml

    - name: Config git
      run: |
        git remote set-url origin https://github-actions:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Create release branch
      run: |
        git checkout -b release/${{ env.RELEASE_VERSION }}
        git add pubspec.yaml
        git commit -m "Increment version to ${{ env.RELEASE_VERSION }}"
        git push origin release/${{ env.RELEASE_VERSION }}
