name: Create Release and Reflect Diff to Development

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  merge_release_branch_and_create_tag:
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract Release Version
        id: extract_version
        run: |
          RELEASE_BRANCH=${{ github.head_ref }}
          RELEASE_VERSION=${RELEASE_BRANCH#release/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Merge Release Branch to Development
        run: |
          git fetch origin development release/$RELEASE_VERSION
          git checkout -b development origin/development
          git merge --no-ff origin/release/$RELEASE_VERSION
          git push origin development

      - name: Create GitHub Release
        run: |
          gh release create v$RELEASE_VERSION \
            --title "Release $RELEASE_VERSION" \
            --notes "This is the release of version $RELEASE_VERSION."

      - name: Delete Release Branch
        run: |
          git push origin --delete release/$RELEASE_VERSION
